Page 13 added
TheGuyDangerous/FoodCoders pull request #111
Opened 2024-01-16 10:01 UTC by bhavkushwaha

-   [X] I have starred and forked the repo
-   [X] I read the instructions to submit the page.
-   [X] I have created a new page, inside a folder named `html-files`.
-   [X] I have edited page 12 Next Page Button in the last page of given code to link it to the new page.
-   [X] I have successfully added 6 new recipes, that are not recurring.
-   [X] I have added all the images inside a separate folder in Image directory named after my page name.
-   [X] I have uploaded all the images to the images folder and the total storage occupied by them is under 500kb.
-   [X] I understand that no image links should be used. All the images should be uploaded.
-   [X] I understand that a reviewer will merge my pull request after review, and that I must comply to recieving code reviews.

2024-01-16 18:47 UTC, TheGuyDangerous requested changes

2024-01-16 18:47 UTC, TheGuyDangerous commented on images/Page 13/Sushi.jpg
# A Few things todo, before merging the PR ✅

Since a new update, *we require all the images to be in a cutout transparent png format*

### Correct way ✅

<h>

![image](https://github.com/TheGuyDangerous/FoodCoders/assets/78858516/59b2533e-29d3-44fb-beee-cbddc5a225c5)

### Incorrect way ❌

<h>

![image](https://github.com/TheGuyDangerous/FoodCoders/assets/78858516/dbaa47af-71e2-42bc-b242-357abed50afa)

2024-01-16 18:47 UTC, TheGuyDangerous commented on images/Page 13/chowMein.jpg
# A Few things todo, before merging the PR ✅

Since a new update, *we require all the images to be in a cutout transparent png format*

### Correct way ✅

<h>

![image](https://github.com/TheGuyDangerous/FoodCoders/assets/78858516/59b2533e-29d3-44fb-beee-cbddc5a225c5)

### Incorrect way ❌

<h>

![image](https://github.com/TheGuyDangerous/FoodCoders/assets/78858516/dbaa47af-71e2-42bc-b242-357abed50afa)

2024-01-16 18:47 UTC, TheGuyDangerous commented on images/Page 13/gajarKaHalwa.jpg
# A Few things todo, before merging the PR ✅

Since a new update, *we require all the images to be in a cutout transparent png format*

### Correct way ✅

<h>

![image](https://github.com/TheGuyDangerous/FoodCoders/assets/78858516/59b2533e-29d3-44fb-beee-cbddc5a225c5)

### Incorrect way ❌

<h>

![image](https://github.com/TheGuyDangerous/FoodCoders/assets/78858516/dbaa47af-71e2-42bc-b242-357abed50afa)

2024-01-16 18:47 UTC, TheGuyDangerous commented on images/Page 13/kadhiChawal.jpg
# A Few things todo, before merging the PR ✅

Since a new update, *we require all the images to be in a cutout transparent png format*

### Correct way ✅

<h>

![image](https://github.com/TheGuyDangerous/FoodCoders/assets/78858516/59b2533e-29d3-44fb-beee-cbddc5a225c5)

### Incorrect way ❌

<h>

![image](https://github.com/TheGuyDangerous/FoodCoders/assets/78858516/dbaa47af-71e2-42bc-b242-357abed50afa)

2024-01-16 18:47 UTC, TheGuyDangerous commented on images/Page 13/kheer.jpg
# A Few things todo, before merging the PR ✅

Since a new update, *we require all the images to be in a cutout transparent png format*

### Correct way ✅

<h>

![image](https://github.com/TheGuyDangerous/FoodCoders/assets/78858516/59b2533e-29d3-44fb-beee-cbddc5a225c5)

### Incorrect way ❌

<h>

![image](https://github.com/TheGuyDangerous/FoodCoders/assets/78858516/dbaa47af-71e2-42bc-b242-357abed50afa)

2024-01-16 18:47 UTC, TheGuyDangerous commented on images/Page 13/tomatoSoup.jpg
# A Few things todo, before merging the PR ✅

Since a new update, *we require all the images to be in a cutout transparent png format*

### Correct way ✅

<h>

![image](https://github.com/TheGuyDangerous/FoodCoders/assets/78858516/59b2533e-29d3-44fb-beee-cbddc5a225c5)

### Incorrect way ❌

<h>

![image](https://github.com/TheGuyDangerous/FoodCoders/assets/78858516/dbaa47af-71e2-42bc-b242-357abed50afa)

2024-01-16 18:50 UTC, TheGuyDangerous commented
@bhavkushwaha review the changes and send in the updated contents.

Note: Do not open a new PR. Update your fork with the changes and send in a pull request again without closing this one, and it should automatically get updated here.

2024-01-17 08:54 UTC, bhavkushwaha commented
@TheGuyDangerous I have made the required changes. I have added transparent PNG Images of appropriate size mentioned and deleted the previous ones from the Images folder. Also I have changed the path given in the webpage so that the project works properly.
I hope the changes I made meet the mentioned requirements.

2024-01-17 09:10 UTC, TheGuyDangerous approved these changes
Looks Good ! ✅

2024-01-17 09:10 UTC, merged