All Images Converted to Transparent PNG
TheGuyDangerous/FoodCoders pull request #117
Opened 2024-01-20 18:32 UTC by bhavkushwaha

## Submission Checklist ✅
Open a pull request only after you have finished adding your recipes. Please complete the below checklist. Failure to follow these instructions may result in your pull request being closed without review, and may affect your contribution.

**Important**: *Reviewers will review your pull requests when applicable, based on a queue. Not starring the repo, will lead to questions*

-   [X] I have starred and forked the repo
-   [X] I read the instructions to submit the page.
-   [X] I have successfully converted all the Images of the Project into transparent PNG format.
-   [X] I have also organised all the food images of all the pages in folders
-   [X] I have also replaced better images if necessary.
-   [X] I have also made the requied changes in the html files to incorporate the new images and folders.
-   [X] I have added a `reviewer` to this pull request.
-   [X] I understand that a reviewer will merge my pull request after review, and that I must comply to recieving code reviews.

2024-01-20 20:12 UTC, TheGuyDangerous requested changes

2024-01-20 20:12 UTC, TheGuyDangerous commented on images/Page 11/breadpizza.png
the left plate border is overflowing, please fix it

2024-01-20 20:12 UTC, TheGuyDangerous commented on images/Page 11/kaju katli.png
the ```upper, and right plate borders``` are overflowing, please fix it

2024-01-20 20:12 UTC, TheGuyDangerous commented on images/Page 12/bhel-puri.png
the ```left and right plate borders``` are overflowing, please fix it

2024-01-20 20:12 UTC, TheGuyDangerous commented on images/Page 12/khichdi-masala.png
the ```bottom plate border``` is overflowing, please fix it

2024-01-20 20:12 UTC, TheGuyDangerous commented on images/Page 4/malai-kofta.png
```all the plate borders``` are overflowing, please fix it

2024-01-20 20:12 UTC, TheGuyDangerous commented on images/Page 6/burger.png
the ```left and plate borders``` are overflowing, please fix it

2024-01-20 20:12 UTC, TheGuyDangerous commented on images/Page 6/chicken-shawarma.png
the ```right plate border``` is overflowing, please fix it

2024-01-20 20:12 UTC, TheGuyDangerous commented on images/Page 7/Peri-Peri-Cheese-Balls.png
the ```right, bottom, and left plate borders``` are overflowing, please fix it

2024-01-20 20:12 UTC, TheGuyDangerous commented on images/Page 7/murgh-masala.png
the ```right plate border``` is overflowing, please fix it

2024-01-20 20:12 UTC, TheGuyDangerous commented on images/Page 9/alfredo.png
the ```top and bottom plate border``` are overflowing, please fix it

2024-01-20 20:12 UTC, TheGuyDangerous commented on images/Page 11/cutlet.png
the ```upper, and bottom plate borders``` are overflowing, please fix it

2024-01-20 20:12 UTC, TheGuyDangerous commented on images/Page 10/choclate-cake.png
the ```left, and right plate borders``` are overflowing, please fix it

2024-01-20 20:12 UTC, TheGuyDangerous commented on images/Page 10/honey-chilli.png
```all the plate borders``` are overflowing, please fix it

2024-01-20 20:12 UTC, TheGuyDangerous commented on images/Page 10/moong-dal-halwa.png
the ```left, and right plate borders``` are overflowing, please fix it

2024-01-20 20:12 UTC, TheGuyDangerous commented on images/Page 11/thekua.png
the ```bottom plate borders``` are overflowing, please fix it

2024-01-20 20:13 UTC, TheGuyDangerous commented
@bhavkushwaha please fix all the border issues for the above mentioned files, and you're all set !

2024-01-21 06:29 UTC, bhavkushwaha commented
Hey @TheGuyDangerous I have modified all the mentioned Images as per instructed, hope they meet the requirements now.

2024-01-21 06:32 UTC, TheGuyDangerous approved these changes

2024-01-21 06:36 UTC, TheGuyDangerous commented
Great Job and nicely done !! ✅

2024-01-21 06:36 UTC, merged