changed the navbar throughout all pages!
TheGuyDangerous/FoodCoders pull request #119
Opened 2024-01-26 14:39 UTC by pragathish07

I have changed all navbar as same as in home page throughout all the pages as metioned , I followed all the instructions mentioned, the code is well structured without disturbing the previous code

Hope this changes helps :) @TheGuyDangerous

2024-01-27 06:18 UTC, pragathish07 commented
before 
![Screenshot (3)](https://github.com/TheGuyDangerous/FoodCoders/assets/91775771/5aa0583a-8cbd-48c0-898d-243402c1ecea)

after adding the same navbar
![Screenshot (6)](https://github.com/TheGuyDangerous/FoodCoders/assets/91775771/d9308204-ec55-4711-83f2-c2f4397bb370)

2024-01-27 17:10 UTC, TheGuyDangerous requested changes

2024-01-27 17:10 UTC, TheGuyDangerous commented on html-files/pages/Page10.html
> +                  <li><a href="./html-files/pages/Page1.html">Recipes<span class="underline"></span></a></li>
use ```./Page1.html``` instead. This error is causing the site to have wrong redirection to all the pages Mentioned below -
- Page 2
- Page 4
- Page 5
- Page 6
- Page 7
- Page 8
- Page 9
- Page 10
- Page 11
- Page 12
- Page 13

when the user taps on ```Recipes``` button in the Navbar

2024-01-27 17:10 UTC, TheGuyDangerous commented on html-files/pages/Page10.html
> +              <a href="index.html"><img height="50" src="https://ik.imagekit.io/daringbaba/Food_Coders/Screenshot_2022-12-23_160309-removebg-preview.png?ik-sdk-version=javascript-1.4.3&updatedAt=1671
at ```<a href="index.html"><img height="50"``` on line 36/37

use ```/index.html``` instead. 

This error is causing false redirection to a page that don't exist.

![image](https://github.com/TheGuyDangerous/FoodCoders/assets/78858516/e57a6d02-2778-49de-bc83-b145c54676c3)


- The following error is happening on all the pages. Fix it, send in an update(do not close the PR, as sending in another PR through your forked repo, will update your changes here) and you'll be good to go ✅

2024-01-27 17:11 UTC, TheGuyDangerous commented
Hi @pragathish07 fix the code review issues, and you'll be good to go ✅

2024-01-31 05:59 UTC, closed without merging

2024-01-31 06:01 UTC, TheGuyDangerous requested changes
Fix the media content overflow issue in the navbar, when opened on a mobile device screen.
- A reference for the same is attached below -
![Mobile ss](https://github.com/TheGuyDangerous/FoodCoders/assets/78858516/49f62cdb-0c18-4bdb-ad78-121b862ac5c6)

- Also , update the newer pages, by fetching the latest changes made , since your last commit.